version: '3'
services:
  web:
    build: .
    image: pythonapp:latest
    container_name: pythonApp
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    restart: unless-stopped
